# Generated by Django 4.2 on 2023-06-18 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_desc', models.TextField()),
                ('image', models.ImageField(upload_to='product_images')),
                ('orginal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category')),
                ('related_products', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_desc', models.TextField()),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('ice', models.DecimalField(choices=[(10, '10%'), (20, '20%'), (50, '50%'), (100, '100%')], decimal_places=0, max_digits=3)),
                ('sugar', models.DecimalField(choices=[(10, '10%'), (50, '50%'), (100, '100%')], decimal_places=0, max_digits=3)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product')),
            ],
        ),
    ]
